name: Deploy to VPS

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to deploy (branch/tag/sha)'
        required: false
        default: 'main'
      allow_builtin:
        description: 'Temporarily allow builtin source / skip strict checks (true/false)'
        required: false
        default: 'false'
      skip_health:
        description: 'Skip health checks (true/false)'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy over SSH (key or password)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          command_timeout: 30m
          script: |
            set -Eeuo pipefail
            BRANCH="${{ github.event.inputs.ref }}"; [ -z "$BRANCH" ] && BRANCH="main"
            # Optional flags to relax checks during first setup/debug
            if [ "${{ github.event.inputs.allow_builtin }}" = "true" ]; then export DEPLOY_ALLOW_BUILTIN=1; fi
            if [ "${{ github.event.inputs.skip_health }}" = "true" ]; then export DEPLOY_SKIP_HEALTH=1; fi
            REPO_DIR=/var/www/html/RepFinder
            APP_DIR="$REPO_DIR/web"
            command -v pm2 >/dev/null || npm i -g pm2
            if [ ! -d "$REPO_DIR/.git" ]; then
              mkdir -p "$REPO_DIR"
              git clone https://github.com/${{ github.repository }} "$REPO_DIR"
            fi
            cd "$REPO_DIR"
            git fetch --all --prune
            git reset --hard "origin/${BRANCH}"
            cd "$APP_DIR"
            bash scripts/deploy.sh

      - name: Show deployed commit
        env:
          REF: ${{ github.event.inputs.ref }}
        run: |
          echo "Deployed ref: ${REF:-$GITHUB_SHA}"
